export const Types = {
    SET_VALUE: 'SET_VALUE',
    RESET_VALUE: 'RESET_VALUE',
    DELETE: 'DELETE',
    SET_EQUATION: 'SET_EQUATION',
    RESET_EQUATION: 'RESET_EQUATION',
    DELETE_EQUATION: 'DELETE_EQUATION',
    NEXT_EQUATION: 'NEXT_EQUATION',
    GET_RESULT: 'GET_RESULT',
}